{% set name = "optuna-dashboard" %}
{% set version = "0.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 07dc73a4a7b95ba2f45e20f404622f2684291024082e7ca1620d3db0dd4fa794

build:
  number: 0
  noarch: python
  entry_points:
    - optuna-dashboard = optuna_dashboard._cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - bottle >=0.13.0
    - optuna >=2.7
    - packaging
    - python >={{ python_min }}
    - scikit-learn

test:
  imports:
    - optuna_dashboard
  commands:
    - pip check
    - optuna-dashboard --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/optuna/optuna-dashboard
  summary: Real-time dashboard for Optuna.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nabenabe0928
    - c-bata
    - g-votte
    - HideakiImamura
    - hvy
    - iwiwi
    - not522
    - sile
    - smly
    - toshihikoyanase
    - ytsmiling
