{% set name = "optuna-dashboard" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 59866b7c5322153cdf777cba701e5ca1d1142f1cff9974976d2295c4c01d79dc

build:
  number: 0
  noarch: python
  entry_points:
    - optuna-dashboard = optuna_dashboard._cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.7
  run:
    - bottle >=0.13.0
    - optuna >=2.7
    - packaging
    - python >=3.7
    - scikit-learn

test:
  imports:
    - optuna_dashboard
  commands:
    - pip check
    - optuna-dashboard --help
  requires:
    - pip

about:
  home: https://github.com/optuna/optuna-dashboard
  summary: Real-time dashboard for Optuna.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nabenabe0928
    - c-bata
    - g-votte
    - HideakiImamura
    - hvy
    - iwiwi
    - not522
    - sile
    - smly
    - toshihikoyanase
    - ytsmiling
